### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by Progi1984**

### CODE REVIEW

**Comment by sarahdib** [comment]
I have this error when I try to test this pr or master or dev 
Capture d’écran 2020-06-17 à 15 09 25

**Comment by Quetzacoalt91** [comment]
Hey,

The module dependencies should be loaded when the core ones do not exists. Can you please follow https://devdocs.prestashop.com/1.7/modules/concepts/composer/#setup-composer-in-a-module so your autoloader is loader is placed at the end of the autoloaders list with `"prepend-autoloader": false`?

**Comment by matks** [comment]
@sarahdib Bug should be fixed now 😄

**Comment by Progi1984** [comment]
Thanks @sarahdib

**Pull request merged**
