### PR TITLE
Add missing payment logo for checkout

### PR DESCRIPTION
**Pull request by dkarvounaris**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no

Unlike most other payment modules that include a logo by default, the wire payment module does not, resulting by default with many themes in inconsistent presentation during checkout and a suboptimal user experience for customers. 

This pull request aims to address this issue by setting the module's logo as the default logo to be displayed. With this change, shop owners can easily replace the default logo with a custom one (the image's URL can reveal its location), as otherwise, there is no clear indication of how to add a payment logo. Without this change, modifying the module's source code to add a logo can be more challenging and problematic during module upgrades.

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by ghost — APPROVED** [review]
It would be nice to have an issue related to the PR

**Comment by Hlavtox** [comment]
@dkarvounaris Hello, I would like to ask you if you could do the same for https://github.com/PrestaShop/ps_cashondelivery/ and https://github.com/PrestaShop/ps_wirepayment so we have all native payment modules unified? :-) I like this change, but it would look weird if we had the icons only on one module.

**Comment by dkarvounaris** [comment]
@Hlavtox Yes, of course. I would love to. I actually had also thought to add a more appropriate logo, but then I just went for the default module logo, as a quick search wasn't helpful to find something with an appropriate license and I weren't sure if that would be "acceptable". If someone is willing to provide some alternative (probably without round edges, white background), and that is also desired, I would add these instead.

**Comment by dkarvounaris** [comment]
> It would be nice to have an issue related to the PR

@okom3pom Let me see how I do this for modules (any hint what the current/best approach is?). It's been some years I made contributions to PrestaShop. I stopped doing so, as back then (long ago!) even essential things weren't easily merged or nobody did care for months or years until everything was outdated to be merged. But things have changed a lot since then and as currently working intensively with it, I thought let's try again.

**Comment by AureRita** [comment]
Hi @dkarvounaris 

Thank you for your PR, when I tested your PR, I see that the images of ps_wirepayement isn't the image that you set up in `views/img` as you can see here : 

image

Is it what your improvement want to do ? 
If yes, why did you set : `->setLogo(_MODULE_DIR_ . '/ps_wirepayment/views/img/logo.png')` ?

**Comment by Hlavtox** [comment]
@AureRita Checkout logo, not module logo in BO.

**Review by MhiriFaten — APPROVED** [review]
Hello @dkarvounaris ,

LGTM ! It is QA approved :heavy_check_mark: 

Thank you!

**Comment by nicosomb** [comment]
Thank you @dkarvounaris and @MhiriFaten !

**Pull request merged**
