### PR TITLE
Uninstall module used on PS 1.6 before using this one

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Comment by kpodemski** [comment]
Hey @Quetzacoalt91 

i'm wondering, how does it work? `uninstall` method in `bankwire` module deletes all `Configuration` entries, why there's no code to migrate those data to new module?

**Comment by Quetzacoalt91** [comment]
Hi @kpodemski,

The trick is to make sure the `uninstall` method is not called. To to so, I redefine this method and override the existing one with the reflexion methods. If you look in `uninstallPrestaShop16Module()`, the new method will only call the same method `uninstall()` from the parent class, and that's it.

This prevents the configuration data to be erased, but the module to be uninstalled anyway and its hooks removed. :)

**Comment by sarahdib** [comment]
after upgrading from 1.6.1.14 to 1.7.6.5 the module isn't upgrade

**Comment by matks** [comment]
@Quetzacoalt91 As I explained [in this issue](https://github.com/PrestaShop/PrestaShop/issues/26973) I will clean our open PRs backlog and close these stale PRs. But I hope that one day we get some bandwidth to reopen this topic, and when it happens, we'll reopen these PRs, find the issues noticed by QA, fix them and merge them ❤️  .

**Pull request closed without merging**
