### PR TITLE
Resize logo for the checkout page

### LINKED ISSUE #35053: Payment method logo wrongly displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The modules on the dev branch:
- ps_checkpayment
- ps_wirepayment
- ps_cashondelivery

since the new feature displays the logo of the payment method into the cart. The logo can be wrongly displayed, and the merchant would need to adapt the theme.

### Expected behavior

To avoid forcing the merchant to adapt the theme, the feature should be configurable. 

Add a toggle on the module, to be able to display or not the logo on the configuration page.
**Label**:Display the payment logo on the payment step
Capture d’écran 2024-01-16 à 14 09 12

By default disabled the feature

### Steps to reproduce

1. Install the module dev branch 
2. go to the checkout page, on the payment step

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Resize logo for the checkout page
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#35053
| How to test?  | Go to checkout page check that the logo is not too big no (40px wide)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @jolelievre 

Thank you for your PR, I tested it and it seems to works as you can see : 

image

Unfortunately and as you seen it, the text is not centered with the check box. 

Moreover, we still have this type of exception when we install the module : 

image

If, despite this, @PrestaShop/product-council is agrees with the solution, It'll be QA :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
I don't think this is a correct solution, what if my theme displays the logo bigger than 40x40 pixels?
The logo should be styled properly by the theme.

**Comment by kpodemski** [comment]
I remember we discussed with @MatShir removing the logo entirely or adding a setting. Now logo is small making it blurry on higher-dpi displays and it doesn't really fix anything  🤔

**Comment by MatShir** [comment]
We need to fix the theme as well. Since it is an old native feature to add a logo on the payment method. I'm wondering if theme and payment module has adapted themselves since then to have a correct display. So, if we provide a fix on the theme, we should, may be only worry for HB theme. 
The test on HB shows that we don't break down on the line
image
But, big pic are still not resized 
image

**Pull request closed without merging**
