### PR TITLE
Bump version to 2.1.0 and Improve project

### PR DESCRIPTION
**Pull request by Progi1984**

### CODE REVIEW

**Comment by Progi1984** [comment]
@PierreRambaud No need QA. (File update & License)

**Comment by Progi1984** [comment]
@PierreRambaud Rebased on `dev` branch

**Comment by PierreRambaud** [comment]
Thanks @Progi1984

**Comment by matks** [comment]
@Progi1984 @PierreRambaud Hey guys what is this ? I see you run PHPStan on Travis. Is it something we plan to do in all modules ? If yes are we sure it's not going to "vampirise" our builds time on Travis ?

I'm surprised because our friends have done this through GitHub Actions on PS Checkout (https://github.com/PrestaShopCorp/ps_checkout/blob/master/.github/workflows/php.yml) so should'nt we try to harmonize our CI with them ?

**Comment by Progi1984** [comment]
@matks No decision has been taken for the projet. Could you propose an ADR for this ?

**Pull request merged**
