### PR TITLE
Release 2.1.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.1.2
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release test

### Version 2.1.2 content

https://github.com/PrestaShop/ps_wirepayment/pull/71 Bump version
https://github.com/PrestaShop/ps_wirepayment/pull/70 PHP 8.1 compatibility
https://github.com/PrestaShop/ps_wirepayment/pull/69 Improvement for CI
https://github.com/PrestaShop/ps_wirepayment/pull/68 Refactoring and cleaning
https://github.com/PrestaShop/ps_wirepayment/pull/67 Hook bugfix

### CODE REVIEW

**Comment by matks** [comment]
@atomiix I approve the PR but is it relevant to release a 2.1.2 with php8.1 compatibility? Maybe it should be a 2.2.0 ?

**Comment by atomiix** [comment]
@matks I see your point but [the fix to make the module compatible with PHP 8.1](https://github.com/PrestaShop/ps_wirepayment/pull/70/files) doesn't look like a new feature but more like a bug fix to me.

**Review by florine2623 — COMMENTED** [review]
Hello @atomiix ,

Thanks for the PR.

I tested with on `1.7.8.x` and `develop` branch and with PHP `7.4`, `8.0`.

- bump version from 2.1.1 to 2.1.2 
- fixed hook function name for hook displayPaymentReturn
- ps_wirepayment module features (BO configuration, check in FO if display is ok, checked order, status is correct)

For 7.4 and 8.0 it is OK.

But for PHP 8.1 I have an error like this on the BO with debug mode enabled: 
image
And on the FO with debug mode enabled, I have a blank page.

Could you check ?
Thanks!

**Comment by atomiix** [comment]
@florine2623 this is normal, those errors does not come from the module but from the core because it is not yet compatible with PHP 8.1.

**Review by florine2623 — APPROVED** [review]
@atomiix ,

Thanks for the info ! 
I have done some more tests and it is looking good to me :)
It is QA ✅

**Comment by Progi1984** [comment]
Thanks @atomiix & @florine2623

**Pull request merged**
