### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release new version 2.2.0
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by ShaiMagal — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hi @Hlavtox ,

The logo seems a little bit big 😅 

Screenshot 2024-01-09 at 17 26 49

Can we have a smaller size ?
Thanks ^^

**Comment by Hlavtox** [comment]
@florine2623 Yep, but we need to fix it on theme side. If we make it smaller here, it doesn't solve anything and on some themes, it could be too small. :)

**Comment by florine2623** [comment]
ping @PrestaShop/product-council ,

As discussed with @Hlavtox , the logo should not be displayed as big as it is on hummingbird/classic.
The theme needs to handle it. But for now, both our themes do not.

@Hlavtox has suggested to add an option to display/hide the logo.
What do you think ?

For now the release should not be validated as is.

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for your PR, to show it with a little icon, that what I have : 

image

I think we can put an issue on the radio button, or as you said maybe hide it with an option

**Comment by MatShir** [comment]
We need to add a switch on this feature. If we don't want to have shops with the varicella. @Hlavtox do you know if the feature has been implemented all our native payment module ?

**Review by MatShir — CHANGES_REQUESTED** [review]
Blocked until the features are fixed (Issue to fix https://github.com/PrestaShop/PrestaShop/issues/35053)

**Review by MatShir — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(118).webm](https://github.com/PrestaShop/ps_wirepayment/assets/100699445/87366fa3-d5e4-4d3a-a7ad-b76ff18f2b2d)

Tested on 8.1.x and develop

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
Thank you @AureRita! :-)

**Pull request merged**
